### ISSUE TITLE
WP3.5 April-Sept-20

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lsst-ir-fusion#18]
- [x] WP 3.5.1	Copy HSC and VISTA data (flat files) to IRIS HPC.
- [x] WP 3.5.2	Configure VISTA metadata to comply with processing using lsst stack
- [x] WP 3.5.3	Install lsst stack pipeline on IRIS HPC and run some timing tests
- [ ] WP 3.5.4	Interface with DAC team to ensure HSC and VISTA catalogues and metadata tables are accessible to this WP

**Comment by tms-epcc** [comment]
Updated checkboxes 3.5.1, 3.5.2, 3.5.3 in description above following Slack exchange with Raphael Shirley on 30/OCT/20.

**Comment by tms-epcc** [comment]
Ticket closed since replaced by Oct'20 to March'21 plan
